// src/main.rs
use std::env;
use std::fs;
use std::time::Duration;

// Generated by `cargo run --bin gen_ascii` from `neofetch_source.sh`.
// Contains `get_ascii(name) -> Option<(&'static str, [u8; 6])>`.
include!("ascii_data.rs");

/// All system information needed for the output.
struct SysInfo {
    username: String,
    hostname: String,
    os_name: String,
    os_id: String,
    os_like: String,
    host_model: String,
    kernel: String,
    uptime: String,
    packages: String,
    shell: String,
    de: String,
    cpu: String,
    memory: String,
}

fn main() {
    let info = get_sys_info();

    // Build a list of candidate keys to look up the ASCII art.
    // Order matters: most specific first, generic last.
    let mut candidates: Vec<String> = Vec::new();
    candidates.push(info.os_name.clone()); // e.g. "Linux Mint 22.3"
    if !info.os_id.is_empty() {
        candidates.push(info.os_id.clone()); // e.g. "linuxmint"
        candidates.push(format!("{}_small", info.os_id)); // e.g. "linuxmint_small"
    }
    if !info.os_like.is_empty() {
        // ID_LIKE can contain several space-separated values, e.g. "ubuntu debian"
        for like in info.os_like.split_whitespace() {
            candidates.push(like.to_string());
        }
    }
    candidates.push(format!("{}_small", info.os_name));
    // Drop empty / whitespace-only entries just in case.
    candidates.retain(|s| !s.trim().is_empty());

    // Look up the art. `get_ascii` is a generated match on prefixes,
    // so the first hit wins. Candidates are ordered above so that
    // "linux mint" wins over "linux".
    let mut art_and_colors = None;
    for cand in &candidates {
        if let Some(x) = get_ascii(cand) {
            art_and_colors = Some(x);
            break;
        }
    }

    // Fallback: Tux the penguin, green/white.
    let (raw_art, colors) = art_and_colors.unwrap_or_else(|| {
        (
            "     .--.\n    |o_o |\n    |:_/ |\n   //   \\ \\\n  (|     | )\n /'\\_   _/`\\\n \\___)=(___/\n",
            [2u8, 7, 7, 7, 7, 7],
        )
    });

    // Convert neofetch color numbers (0..=8, or 256-color index) to ANSI SGR codes.
    // 0..=6  -> basic bold colors 30..36
    // 7      -> bold white
    // 8      -> bold bright black (gray)
    // other  -> 256-color foreground
    let ansi = |n: u8| -> String {
        match n {
            0..=6 => format!("\x1b[1;3{}m", n),
            7 => "\x1b[1;37m".to_string(),
            8 => "\x1b[1;90m".to_string(),
            _ => format!("\x1b[1;38;5;{}m", n),
        }
    };

    // Pre-resolve ANSI codes for each of the 6 slots.
    let c: Vec<String> = colors.iter().map(|&n| ansi(n)).collect();

    // Replace ${c1}..${c6} placeholders in the art with real ANSI codes.
    let mut art_lines: Vec<String> = Vec::new();
    for line in raw_art.lines() {
        let mut s = line.to_string();
        for (i, code) in c.iter().enumerate() {
            s = s.replace(&format!("${{c{}}}", i + 1), code);
        }
        art_lines.push(s);
    }

    // Colors for the right-hand info block.
    let green = "\x1b[1;32m";
    let reset = "\x1b[0m";

    // Header: "user@hostname" with an underline of matching length.
    let header = format!(
        "{g}{u}{r}@{g}{h}{r}",
        g = green,
        u = info.username,
        r = reset,
        h = info.hostname
    );
    let underline = format!(
        "{}{}",
        green,
        "-".repeat(info.username.len() + info.hostname.len() + 1)
    );

    // Info rows. Labels are green, values are default color.
    let info_lines = vec![
        format!("{}OS:{}         {}", green, reset, info.os_name),
        format!("{}Host:{}       {}", green, reset, info.host_model),
        format!("{}Kernel:{}     {}", green, reset, info.kernel),
        format!("{}Uptime:{}     {}", green, reset, info.uptime),
        format!("{}Packages:{}   {}", green, reset, info.packages),
        format!("{}Shell:{}      {}", green, reset, info.shell),
        format!("{}DE:{}         {}", green, reset, info.de),
        format!("{}CPU:{}        {}", green, reset, info.cpu),
        format!("{}Memory:{}     {}", green, reset, info.memory),
    ];

    // Print line by line: art on the left, info on the right.
    // The first two lines of the right column are the header and underline.
    let max_lines = art_lines.len().max(info_lines.len() + 2);
    for i in 0..max_lines {
        if i < art_lines.len() {
            print!("{}", art_lines[i]);
            // Pad the art column to a fixed width so the info always starts at the same x.
            let raw_width = visible_width(raw_art.lines().nth(i).unwrap_or(""));
            let needed = 43usize.saturating_sub(raw_width) + 3;
            print!("{}{}", " ".repeat(needed), reset);
        } else {
            // Art is shorter than info: pad with plain spaces.
            print!("{}", " ".repeat(46));
        }

        if i == 0 {
            println!("{}", header);
        } else if i == 1 {
            println!("{}", underline);
        } else if i - 2 < info_lines.len() {
            println!("{}", info_lines[i - 2]);
        } else {
            println!();
        }
    }
}

/// Width of a string as it will appear on screen:
/// count chars after removing `${cN}` placeholders.
fn visible_width(s: &str) -> usize {
    let mut tmp = s.to_string();
    for i in 1..=6 {
        tmp = tmp.replace(&format!("${{c{i}}}"), "");
    }
    tmp.chars().count()
}

/// Collect system information from /proc, /sys, /etc and environment variables.
fn get_sys_info() -> SysInfo {
    let username = env::var("USER").unwrap_or_else(|_| "user".to_string());

    let hostname = fs::read_to_string("/proc/sys/kernel/hostname")
        .unwrap_or_else(|_| "unknown".into())
        .trim()
        .to_string();

    // Parse /etc/os-release. We take PRETTY_NAME (for display) and
    // ID / ID_LIKE (for matching against the ASCII art keys).
    let mut os_name = "Linux".to_string();
    let mut os_id = String::new();
    let mut os_like = String::new();
    if let Ok(release) = fs::read_to_string("/etc/os-release") {
        for line in release.lines() {
            if let Some(v) = line.strip_prefix("PRETTY_NAME=") {
                os_name = v.trim_matches('"').to_string();
            } else if let Some(v) = line.strip_prefix("NAME=") {
                // Fallback if PRETTY_NAME is missing.
                if os_name == "Linux" {
                    os_name = v.trim_matches('"').to_string();
                }
            } else if let Some(v) = line.strip_prefix("ID=") {
                os_id = v.trim_matches('"').to_string();
            } else if let Some(v) = line.strip_prefix("ID_LIKE=") {
                os_like = v.trim_matches('"').to_string();
            }
        }
    }

    let host_model = fs::read_to_string("/sys/devices/virtual/dmi/id/product_name")
        .unwrap_or_else(|_| "unknown".into())
        .trim()
        .to_string();

    // Kernel version: the 3rd whitespace-separated field of /proc/version.
    let kernel = fs::read_to_string("/proc/version")
        .map(|s| {
            s.split_whitespace()
                .nth(2)
                .unwrap_or("unknown")
                .to_string()
        })
        .unwrap_or_else(|_| "unknown".into());

    // Uptime: parse seconds from /proc/uptime, then format as
    // "N days, H hours, M mins" with smart plural/empty handling.
    let uptime_str = fs::read_to_string("/proc/uptime").unwrap_or_else(|_| "0".into());
    let secs = uptime_str
        .split_whitespace()
        .next()
        .unwrap_or("0")
        .parse::<f64>()
        .unwrap_or(0.0) as u64;
    let d = Duration::from_secs(secs);
    let mins = (d.as_secs() % 3600) / 60;
    let hours = (d.as_secs() % 86400) / 3600;
    let days = d.as_secs() / 86400;
    let uptime = if days > 0 {
        format!("{} days, {} hours, {} mins", days, hours, mins)
    } else if hours > 0 {
        format!("{} hours, {} mins", hours, mins)
    } else {
        format!("{} mins", mins)
    };

    // Packages: count installed entries in dpkg's status file.
    // For other package managers you'd add more counters here.
    let mut pkgs = 0;
    if let Ok(status) = fs::read_to_string("/var/lib/dpkg/status") {
        for line in status.lines() {
            if line.starts_with("Status: install ok installed") {
                pkgs += 1;
            }
        }
    }

    // Current shell: basename of $SHELL.
    let shell = env::var("SHELL")
        .unwrap_or_else(|_| "bash".into())
        .split('/')
        .last()
        .unwrap_or("bash")
        .to_string();

    // Desktop environment. Currently hardcoded to Cinnamon since this
    // is a Mint-focused build; add more branches if you need them.
    let session = env::var("XDG_SESSION_TYPE").unwrap_or_default();
    let de = if session.eq_ignore_ascii_case("wayland") {
        "Cinnamon (Wayland)".into()
    } else {
        "Cinnamon".into()
    };

    // CPU model name: first "model name" line in /proc/cpuinfo.
    let mut cpu = "Unknown".to_string();
    if let Ok(cpuinfo) = fs::read_to_string("/proc/cpuinfo") {
        for line in cpuinfo.lines() {
            if line.starts_with("model name") {
                cpu = line.split(':').nth(1).unwrap_or("").trim().to_string();
                break;
            }
        }
    }

    // Memory: total and available (in kB) from /proc/meminfo.
    let mut mem_total = 0u64;
    let mut mem_avail = 0u64;
    if let Ok(meminfo) = fs::read_to_string("/proc/meminfo") {
        for line in meminfo.lines() {
            if line.starts_with("MemTotal:") {
                mem_total = parse_kb(line);
            } else if line.starts_with("MemAvailable:") {
                mem_avail = parse_kb(line);
            }
        }
    }
    let mem_used = mem_total.saturating_sub(mem_avail);
    let memory = format!("{}MiB / {}MiB", mem_used / 1024, mem_total / 1024);

    SysInfo {
        username,
        hostname,
        os_name,
        os_id,
        os_like,
        host_model,
        kernel,
        uptime,
        packages: format!("{} (dpkg)", pkgs),
        shell,
        de,
        cpu,
        memory,
    }
}

/// Parse the first numeric field of a /proc/meminfo line (value in kB).
fn parse_kb(line: &str) -> u64 {
    line.split_whitespace()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(0)
}
